class GeneralData {
  final double? idHojaVida,
      idProcesoElectoral,
      idTipoEleccion,
      numeroCandidato,
      idOrganizacionPolitica,
      idSolicitudLista;
  final String numeroDocumento,
      nombres,
      apellidoPaterno,
      apellidoMaterno,
      sexo,
      feNacimiento,
      paisNacimiento,
      ubigeoNacimiento,
      naciDepartamento,
      naciProvincia,
      naciDistrito,
      ubigeoDomicilio,
      domiDepartamento,
      domiProvincia,
      domiDistrito,
      domicilioDirecc,
      ubigeoPostula,
      postulaDepartamento,
      postulaProvincia,
      postulaDistrito,
      rutaArchivo,
      estado,
      organizacionPolitica,
      txFeTerminoRegistro,
      txGuidFormatoHojaVida;
  final String? txComentario;
  final List<String>? cargo;

  GeneralData({
    this.idHojaVida,
    this.idProcesoElectoral,
    this.idTipoEleccion,
    this.numeroCandidato,
    this.idOrganizacionPolitica,
    this.idSolicitudLista,
    required this.numeroDocumento,
    required this.nombres,
    required this.apellidoPaterno,
    required this.apellidoMaterno,
    required this.sexo,
    required this.feNacimiento,
    required this.paisNacimiento,
    required this.ubigeoNacimiento,
    required this.naciDepartamento,
    required this.naciProvincia,
    required this.naciDistrito,
    required this.ubigeoDomicilio,
    required this.domiDepartamento,
    required this.domiProvincia,
    required this.domiDistrito,
    required this.domicilioDirecc,
    required this.ubigeoPostula,
    required this.postulaDepartamento,
    required this.postulaProvincia,
    required this.postulaDistrito,
    required this.rutaArchivo,
    required this.estado,
    required this.organizacionPolitica,
    required this.txFeTerminoRegistro,
    required this.txGuidFormatoHojaVida,
    this.txComentario,
    this.cargo,
  });

  factory GeneralData.fromJson(Map<String, dynamic> json) {
    var list = json['cargo'];
    List<String> cargoList = List<String>.from(list);

    return GeneralData(
      idHojaVida: json['idHojaVida'],
      idProcesoElectoral: json['idProcesoElectoral'],
      idTipoEleccion: json['idTipoEleccion'],
      numeroCandidato: json['numeroCandidato'],
      idOrganizacionPolitica: json['idOrganizacionPolitica'],
      idSolicitudLista: json['idSolicitudLista'],
      numeroDocumento: json['numeroDocumento'],
      nombres: json['nombres'],
      apellidoPaterno: json['apellidoPaterno'],
      apellidoMaterno: json['apellidoMaterno'],
      sexo: json['sexo'],
      feNacimiento: json['feNacimiento'],
      paisNacimiento: json['paisNacimiento'],
      ubigeoNacimiento: json['ubigeoNacimiento'],
      naciDepartamento: json['naciDepartamento'],
      naciProvincia: json['naciProvincia'],
      naciDistrito: json['naciDistrito'],
      ubigeoDomicilio: json['ubigeoDomicilio'],
      domiDepartamento: json['domiDepartamento'],
      domiProvincia: json['domiProvincia'],
      domiDistrito: json['domiDistrito'],
      domicilioDirecc: json['domicilioDirecc'],
      ubigeoPostula: json['ubigeoPostula'],
      postulaDepartamento: json['postulaDepartamento'],
      postulaProvincia: json['postulaProvincia'],
      postulaDistrito: json['postulaDistrito'],
      rutaArchivo: json['rutaArchivo'],
      estado: json['estado'],
      organizacionPolitica: json['organizacionPolitica'],
      txFeTerminoRegistro: json['txFeTerminoRegistro'],
      txGuidFormatoHojaVida: json['txGuidFormatoHojaVida'],
      txComentario: json['txComentario'],
      cargo: cargoList,
    );
  }
}
