class Parliament {
  final int? idOrganizacionPolitica,
      idCandidato,
      idEstado,
      idCargo,
      intPosicion,
      idTipoEleccion,
      idAutoridad,
      idAutoridadReemplazo,
      idParamTipoReemplazo,
      idPeriodoGob,
      idConformacion,
      idConformacionDetalle,
      intOrden,
      idHojaVida,
      idPlanGobierno,
      intExpedientes,
      idCredencialConf,
      idCandidatoReemplazado,
      intEscanios,
      intEscaniosObtenidos,
      intVotoPreferencial,
      idProcesoElectoral;

  final String? strOrganizacionPolitica,
      strIdOrgPoliticaOnpe,
      strObservacion,
      strSexo,
      strEstado,
      strDocumentoIdentidad,
      strNombres,
      strApellidoPaterno,
      strApellidoMaterno,
      strResultado,
      strCargo,
      strCargoAnterior,
      strUbigeoPostula,
      strUbiProvConsejero,
      strProvinciaConsejero,
      strTipoEleccion,
      strIdTipoEleccion,
      strFechaInicioVigencia,
      strFechaFinVigencia,
      strParamTipoReemplazo,
      strRutaFoto,
      strDepartamento,
      strProvincia,
      strDistrito,
      strRutaPlanGob,
      strReemplaza,
      strUbigeo,
      strCodCredencial,
      strEsNuevo,
      strIdDistritoElectoral,
      strDistritoElectoral,
      strCandidato,
      strCondicion,
      strProcesoElectoral,
      strOrgPoliticaReemplaza,
      strTipoReemplazo,
      strEsReemplazo;

  Parliament(
      {this.idOrganizacionPolitica,
      this.idCandidato,
      this.idEstado,
      this.idCargo,
      this.intPosicion,
      this.idTipoEleccion,
      this.idAutoridad,
      this.idAutoridadReemplazo,
      this.idParamTipoReemplazo,
      this.idPeriodoGob,
      this.idConformacion,
      this.idConformacionDetalle,
      this.intOrden,
      this.idHojaVida,
      this.idPlanGobierno,
      this.intExpedientes,
      this.idCredencialConf,
      this.idCandidatoReemplazado,
      this.intEscanios,
      this.intEscaniosObtenidos,
      this.intVotoPreferencial,
      this.idProcesoElectoral,
      this.strOrganizacionPolitica,
      this.strIdOrgPoliticaOnpe,
      this.strObservacion,
      this.strSexo,
      this.strEstado,
      this.strDocumentoIdentidad,
      this.strNombres,
      this.strApellidoPaterno,
      this.strApellidoMaterno,
      this.strResultado,
      this.strCargo,
      this.strCargoAnterior,
      this.strUbigeoPostula,
      this.strUbiProvConsejero,
      this.strProvinciaConsejero,
      this.strTipoEleccion,
      this.strIdTipoEleccion,
      this.strFechaInicioVigencia,
      this.strFechaFinVigencia,
      this.strParamTipoReemplazo,
      this.strRutaFoto,
      this.strDepartamento,
      this.strProvincia,
      this.strDistrito,
      this.strRutaPlanGob,
      this.strReemplaza,
      this.strUbigeo,
      this.strCodCredencial,
      this.strEsNuevo,
      this.strIdDistritoElectoral,
      this.strDistritoElectoral,
      this.strCandidato,
      this.strCondicion,
      this.strProcesoElectoral,
      this.strOrgPoliticaReemplaza,
      this.strTipoReemplazo,
      this.strEsReemplazo});

  factory Parliament.fromJson(Map<String, dynamic> json) {
    return Parliament(
      idOrganizacionPolitica: json['idOrganizacionPolitica'],
      strOrganizacionPolitica: json['strOrganizacionPolitica'],
      strIdOrgPoliticaOnpe: json['strIdOrgPoliticaOnpe'],
      idCandidato: json['idCandidato'],
      strObservacion: json['strObservacion'],
      strSexo: json['strSexo'],
      idEstado: json['idEstado'],
      strEstado: json['strEstado'],
      strDocumentoIdentidad: json['strDocumentoIdentidad'],
      strNombres: json['strNombres'],
      strApellidoPaterno: json['strApellidoPaterno'],
      strApellidoMaterno: json['strApellidoMaterno'],
      strResultado: json['strResultado'],
      idCargo: json['idCargo'],
      strCargo: json['strCargo'],
      strCargoAnterior: json['strCargoAnterior'],
      intPosicion: json['intPosicion'],
      strUbigeoPostula: json['strUbigeoPostula'],
      strUbiProvConsejero: json['strUbiProvConsejero'],
      strProvinciaConsejero: json['strProvinciaConsejero'],
      idTipoEleccion: json['idTipoEleccion'],
      strTipoEleccion: json['strTipoEleccion'],
      strIdTipoEleccion: json['strIdTipoEleccion'],
      idAutoridad: json['idAutoridad'],
      strFechaInicioVigencia: json['strFechaInicioVigencia'],
      strFechaFinVigencia: json['strFechaFinVigencia'],
      idAutoridadReemplazo: json['idAutoridadReemplazo'],
      idParamTipoReemplazo: json['idParamTipoReemplazo'],
      strParamTipoReemplazo: json['strParamTipoReemplazo'],
      idPeriodoGob: json['idPeriodoGob'],
      idConformacion: json['idConformacion'],
      idConformacionDetalle: json['idConformacionDetalle'],
      intOrden: json['intOrden'],
      strRutaFoto: json['strRutaFoto'],
      idHojaVida: json['idHojaVida'],
      strDepartamento: json['strDepartamento'],
      strProvincia: json['strProvincia'],
      strDistrito: json['strDistrito'],
      idPlanGobierno: json['idPlanGobierno'],
      strRutaPlanGob: json['strRutaPlanGob'],
      strReemplaza: json['strReemplaza'],
      intExpedientes: json['intExpedientes'],
      strUbigeo: json['strUbigeo'],
      strCodCredencial: json['strCodCredencial'],
      idCredencialConf: json['idCredencialConf'],
      strEsNuevo: json['strEsNuevo'],
      idCandidatoReemplazado: json['idCandidatoReemplazado'],
      strIdDistritoElectoral: json['strIdDistritoElectoral'],
      strDistritoElectoral: json['strDistritoElectoral'],
      intEscanios: json['intEscanios'],
      intEscaniosObtenidos: json['intEscaniosObtenidos'],
      strCandidato: json['strCandidato'],
      intVotoPreferencial: json['intVotoPreferencial'],
      strCondicion: json['strCondicion'],
      idProcesoElectoral: json['idProcesoElectoral'],
      strProcesoElectoral: json['strProcesoElectoral'],
      strOrgPoliticaReemplaza: json['strOrgPoliticaReemplaza'],
      strTipoReemplazo: json['strTipoReemplazo'],
      strEsReemplazo: json['strEsReemplazo'],
    );
  }
}
